#+TITLE: Readme

* Structure of the geometry description

The geometry is divided into several files to make working with it easier.
- [[./detector.gdml][detector.gdml]] This is the entrypoint of the geometry. Contains the actual implementation of the prototype geometry using the definitions from [[./absorber_volume.gdml][absorber_volume.gdml]] and [[./scintillator_volume.gdml][scintillator_volume.gdml]]
- [[./constants.gdml][constants.gdml]] Contains variable definitions used elsewhere in the
  geometry such as positions and geometrical properties of different volumes.
- [[./materials.gdml][materials.gdml]] Contains definitions of isotopes and materials
- [[./userinfo.gdml][userinfo.gdml]] Contains auxiliary information (see the
  [[https://gdml.web.cern.ch/GDML/doc/GDMLmanual.pdf][GDML manual]] for
  details), such as sensitive detector volumes, visualization information,
  version and author information.
- [[./hcal_solids.gdml][hcal_solids.gdml]] Contains definitions of the absorber, scintillator, and parent boxes
- [[./absorber_volume.gdml][absorber_volume.gdml]] Contains the definition of the absorber volume
- [[./scintillator_volume.gdml][scintillator_volume.gdml]] Contains the definition of the scintillator volumes


* Variables

The following is a list of all the variables defined in the protoype geometry description.


** Constants

- =center=, =identity=, and =hadron_calorimeter_pos= are positions that are all
  defined as *(x,y,z) = (0,0,0)*. =hadron_calorimeter_pos= is used to place the
  =prototype_volume= physical volume within the =World= volume.
- =world_dim= is the size of the sides of the "world_box" box, set to *10 m*
- =air_thick= is the thickness (\Delta z_{air}) of the layers of air in between the
  absorber and scintillator bars. The thickness of each region is set to *2 mm*,
  which contributes twice to the thickness of an individual layer.
- =absorber_width= is the width (\Delta x_{absorber},\Delta y_{absorber}) of an absorber
  layer, set to *800 mm*
- =absorber_ears=, TODO: Document this, set to *50 mm*
- =absorber_thickness= is the thickness (\Delta z_{absorber}) of an absorber layer,
  set to *25 mm*
- =scint_thick= is the thickness of a scintillator bar layer (\Delta
  z_{scintillator}). This is equivalent to the thickness of an individual
  scintillator bar and is set to *20 mm*
- =scint_bar_length= is the length of an individual scintillator bar. In
  horizontal layers, this is equivalent to the width (\Delta x_{scintillator}) of the
  layer while in vertical layers it is equivalent to the height (\Delta
  y_{scintillator}) of the layer. It is set to *2000 mm*.
- =layer_thick= is the combined thickness of a layer (\Delta z_{layer}). It consists
  of one layer of absorber, =absorber_thickness=, one layer of scintillators, and /two/ layers and /two/ layers of air, =air_thick=. The resulting layer
  thickness is thus given by =absorber_thickness + scint_thick + 2 * air_thick=, *49 mm*
- =double_layer_thick= is twice the thickness of one layer, i.e. *98 mm*. It is
  currently only used in defining the total depth of the prototype, =dz=.
- =numLayersFront= is the total number of layers in the front region of the
  prototype and is set to *9*
- =numLayersFront_vert= and =numLayersFront_hori= are the number of
  vertical/horizontal layers in the front region. They are set to *4* and *5*
  respectively
- =numDoubleLayersBack= is the number of horizontal or vertical layers in the
  back region. It is set to *5* so the total number of layers in the back region
  is *10*
- =numLayers= is the total number of layers. It is set to *19* and corresponds
  to =numLayers + 2 * numDoubleLayersBack=.
- =back_start= is the location of the first layer in the back region. It is set
  to =numLayersFront * layer_thick=, i.e. *441 mm*.
- The length of the sides of the various scintillator layers are defined as
  + Front vertical layers have =scint_FrontV_x= which is *400 mm*,
    =scint_FrontV_y= which is the bar length, *2000 mm*. The 400 mm corresponds
    to 8 bars each having a width of *50 mm*
  + Front horizontal layers have =scint_FrontH_y= which is *400 mm*,
    =scint_FrontH_x= which is the bar length, *2000 mm*. The 400 mm corresponds
    to 8 bars each having a width of *50 mm*
  + Back vertical layers have =scint_BackV_x= which is *600 mm*, =scint_BackV_y=
    which is the bar length, *2000 mm*. The 600 mm corresponds to 12 bars each
    having a width of *50 mm*
  + Back horizontal layers have =scint_BackH_y= which is *600 mm*,
    =scint_BackH_x= which is the bar length, *2000 mm*. The 600 mm corresponds
    to 12 bars each having a width of *50 mm*
- =dx= and =dy=, the width and height of the prototype respectively are both set
  to *3000 mm*
- =dz= is the depth of the prototype and is defined as =numLayersFront *
  layer_thick + numDoubleLayersBack * double_layer_thick= which correpsonds to
  *931 mm*


** Solids
Solids are objects with purely geometrical properties such as a box, a sphere,
or a more complicated geometry
- =absorberBox= is the solid that represents the absorber layer.
  + TODO: Document this @petergy
- There are four boxes representing the four different types of scintillator
  layers (front vertical, front horizontal, back vertical, back horizontal).
  These are defined using the corresponding width/height from
  [[*Constants][Constants]], e.g.
  + =frontV_ScintBox= has width =scint_FrontV_x= (400 mm) and height
    =scint_FrontV_y= (2000 mm)
  + =frontH_ScintBox= has width =scint_FrontH_x= (2000 mm) and height
    =scint_FrontH_y= (400 mm)
  + =backV_ScintBox= has width =scint_BackV_x= (600 mm) and height
    =scint_BackV_y= (2000 mm)
  + =backH_ScintBox= has width =scint_BackH_x= (2000 mm) and height
    =scint_BackH_y= (600 mm)
- =air_box= is the a box representing a single air layer and has width =dx=
  (3000 mm), height =dy= (3000 mm), and depth =air_thick= (2 mm)
- =prototype_Box= is the parent volume for the prototype and is defined as a box
  with width =dx= (3000 mm), height =dy= (3000 mm), and depth =dz= (931 mm)
- =world_box= is the parent volume for all the other parts of the geometry and
  is defined as a box with all sides having length =world_dim= (10 m)

** Logical volumes

In Geant4, a logical volume can contain all of the information about a volume
except for its position. This allows you to use one logical volume to create
several distinct daughter physical volumes. The position and rotation of a
daughter volume is defined in terms for the mother volume. The logical volumes
that we use in this geometry can contain the following tags
- =<solidref>= is a reference to one of the solids defined in
  [[./hcal_solids.gdml][hcal_solids.gdml]]
- =<materialref>= is a reference to a material defined in
  [[./materials.gdml][materials.gdml]]
- =<auxiliary>= allows us to add any other kind of information that is used by
  the simulation, such as defining if a volume is supposed to be a sensitive
  element or how the volume should be visualized by default. Most auxiliary tags will be references to groups of properties defined in [[*User information][User information]].
- =<physvol>= any daughter volumes that are to be placed within the logical
  volume, see [[*Physical volumes][Physical volumes]]

Furthermore, each logical volume has a name as part of the =<volume>= tag which
can be used to refer to the volume using the =<volumeref>= tag. At least one logical volume has to be the "World" volume. This volume determines the global coordinate system and has to completly contain all other volumes, sharing surfaces with none of them.

- =World= is the "World" volume. It is defined in
  [[./detector.gdml][detector.gdml]]
  + Material: =G4_AIR=
  + Solid: =world_box=
  + Daughter volumes:
    - =prototype_volume=
  + Auxiliary information:
    - "DetElem": "Top"
- =prototype_volume= represents the entire prototype and is defined in
  [[./detector.gdml][detector.gdml]]
  + Material: =G4_AIR=
  + Solid: =prototype_Box=
  + Daughter volumes:
    - =absorber_physvol=
    - =frontH_scint_physvol=
    - =frontV_scint_physvol=
    - =back_H_scint_physvol=
    - =back_V_scint_physvol=
  + Auxiliary information:
    - "Region": "CalorimeterRegion"
    - "VisAttributes": "HcalVis"
    - "DetElem": "Hcal"
- =absorber_volume= represents one layer of the steel absorber and is defined in [[./absorber_volume.gdml][absorber_volume.gdml]]
  + Material: =Steel=
  + Solid: =absorberBox=
  + Auxiliary information:
    - "Color": "Red"
    - "VisAttributes": "HcalVis"
- There are four volumes representing each of the four different types of
  scintillator layers called =frontV_ScintBox_volume=, =frontH_ScintBox_volume=,
  =backV_ScintBox_volume=, and =backH_ScintBox_volume=, all defined in
  [[./scintillator_volume.gdml][scintillator_volume.gdml]]. They differ in name
  and which corresponding solid they make use of
- Material: "Scintillator"
- Solid: One of =frontV_ScintBox=, =frontH_ScintBox=, =backV_ScintBox=, and
  =backH_ScintBox=
- Auxiliary information:
  + "SensDet": "HcalSD"
  + "Color": "Blue"
  + "VisAttributes": "HcalVis"


** Physical volumes


** User information
